micro:
  server:
    name: baseServer
    db-name: base_server_test1
    db:
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
  api-path: /
  eureka:
    base-port: 9001
    instance-quantity: 2 #注册中心高可用最大实例上限
    test-hostname: testadmin.hushijie.com.cn
    local-url: #测试环境地址
    test-url: http://${micro.eureka.test-hostname}:9002/eureka/,http://${micro.eureka.test-hostname}:9001/eureka/ #
    develop-url: http://testadmin.hushijie.com.cn #
    online-url: http://dataplane.hushijie.com.cn #

spring:
  application:
    name: ${micro.server.name}
  datasource:
    db1:
      driver-class-name: ${micro.server.db.driver-class-name}
      platform: ${micro.db.platform}
    #db2数据库一般为只读库
    db2:
      driver-class-name: ${micro.server.db.driver-class-name}
      platform: ${micro.db.platform}

server:
  port: 8080
  context-path: /
  tomcat:
    buffered: true
    uri-encoding: utf-8
    accesslog:
      enabled: true
      directory:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

start-up-config:
  mysql: true
  redis: false

redis-config:
  host: localhost
  port: 6379
  auth:
  maxActive: 200
  maxIdle: 32
  maxWait: 10000
  timeOut: 10000
  testOnBorrow: false
---
spring:
  profiles: zuulTest
  datasource:
    db1:
      url: jdbc:mysql://192.168.1.100:3306/micro_base_server?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: micro_user
      password: qweasdzxc~!@#
    db2:
      url: jdbc:mysql://192.168.1.100:3306/micro_base_server?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: micro_user
      password: qweasdzxc~!@#

zuul:
  routes:
    question-server:
      path: /questionServer/**
      serviceId: question-server

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000

ribbon:
  ConnectTimeout: 100000
  ReadTimeout: 100000
eureka:
  server:
    enableSelfPreservation: false #默认启动自我保护机制
    evictionIntervalTimerInMs: 5000
  instance:
    hostname: ${micro.eureka.test-hostname}
  client:
    serviceUrl:
      defaultZone: ${micro.eureka.test-url}
---
spring:
  profiles: configTest
  datasource:
    db1:
      url: jdbc:mysql://192.168.1.100:3306/micro_base_server?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: micro_user
      password: qweasdzxc~!@#
  cloud:
    config:
      server:
        git:
          uri: http://gitlab.hushijie.com.cn/root/configurationcenter.git
          username: wangqiang
          password: zhbyQMUP,/.

eureka:
  server:
    enableSelfPreservation: false #默认启动自我保护机制
    evictionIntervalTimerInMs: 5000
  instance:
    hostname: ${micro.eureka.test-hostname}
  client:
    serviceUrl:
      defaultZone: ${micro.eureka.test-url}
---
spring:
  profiles: eurekaOnline
  datasource:
    db1:
      url: jdbc:mysql://192.168.1.100:3306/${micro.server.db-name}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: micro_user
      password: qweasdzxc~!@#
    db2:
      url: jdbc:mysql://192.168.1.100:3306/icu_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=Asia/Shanghai
      username: test
      password: 123456

eureka:
  server:
    enableSelfPreservation: true #默认启动自我保护机制
  instance:
    hostname:
  client:
    serviceUrl:
      defaultZone:
---
spring:
  profiles: eurekaTest
  datasource:
    db1:
      url: jdbc:mysql://192.168.1.100:3306/micro_base_server?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: micro_user
      password: qweasdzxc~!@#
    db2:
      url: jdbc:mysql://192.168.1.100:3306/micro_base_server?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: micro_user
      password: qweasdzxc~!@#

eureka:
  server:
    enableSelfPreservation: false #默认启动自我保护机制
    evictionIntervalTimerInMs: 5000
  instance:
    hostname: testadmin.hushijie.com.cn
  client:
    serviceUrl:
      defaultZone: http://testadmin.hushijie.com.cn:9002/eureka/,http://testadmin.hushijie.com.cn:9001/eureka/
---
spring:
  profiles: local
  datasource:
    db1:
      url: jdbc:mysql://192.168.1.100:3306/${micro.server.db-name}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: micro_user
      password: qweasdzxc~!@#
    db2:
      url: jdbc:mysql://192.168.1.100:3306/icu_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=Asia/Shanghai
      username: test
      password: 123456
  data:
    mongodb:
      host: 192.168.1.100
      port: 27017
      authentication-database: admin
      database: ${micro.server.db-name}
      username: root
      password: qweasdzxc~!@#
  mvc:
    static-path-pattern: /api/**
  resources:
    static-locations: ${micro.api-path}


eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 6
  client:
    serviceUrl:
      defaultZone: ${micro.eureka.test-url}
---
spring:
  profiles: develop
  datasource:
    db1:
      url: jdbc:mysql://47.95.148.210:3306/${micro.server.db-name}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: root
      password: Root-123
    db2:
      url: jdbc:mysql://192.168.1.100:3306/icu_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=Asia/Shanghai
      username: test
      password: 123456
  mvc:
    static-path-pattern: /api/**
  resources:
    static-locations: ${micro.api-path}

eureka:
  instance:
    hostname:
  client:
    serviceUrl:
      defaultZone: ${micro.eureka.test-url}
---
spring:
  profiles: test
  datasource:
    db1:
      url: jdbc:mysql://192.168.1.100:3306/${micro.server.db-name}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: micro_user
      password: qweasdzxc~!@#
    db2:
      url: jdbc:mysql://192.168.1.100:3306/icu_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=Asia/Shanghai
      username: test
      password: 123456
  data:
    mongodb:
      uri: mongodb://root:qweasdzxc~!@#@192.168.1.100:27017/${micro.server.db-name}
  mvc:
    static-path-pattern: /api/**
  resources:
    static-locations: ${micro.api-path}

eureka:
  instance:
    hostname: ${micro.eureka.test-hostname}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 6
  client:
    serviceUrl:
      defaultZone: ${micro.eureka.test-url}
---
spring:
  profiles: online
  datasource:
    db1:
      url: jdbc:mysql://47.95.148.210:3306/${micro.server.db-name}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: root
      password: Root-123
    db2:
      url: jdbc:mysql://10.30.56.228:3309/icu?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;failOverReadOnly=false&amp;useSSL=true
      username: icu
      password: qweasdzxc~!@#
  mvc:
    static-path-pattern: /api/**
  resources:
    static-locations: ${micro.api-path}

eureka:
  instance:
    hostname:
  client:
    serviceUrl:
      defaultZone: http://http://dataplane.hushijie.com.cn:9002/eureka/,http://dataplane.hushijie.com.cn:9002/eureka/
---